@startuml
title Запуск сканирования

box "[[/architect/components/platform.platform.scan_management ScanManagement]]"
    participant "[[/architect/components/platform.platform.scan_management.scan_starter ScanStarter]]" as ScanStarter
    participant "[[/architect/components/platform.platform.scan_management.config_manager ConfigManager]]" as ConfigManager
    participant "[[/architect/components/platform.platform.scan_management.source_code_manager SourceCodeManager]]" as SourceCodeManager
end box

box "[[/architect/components/plugins Plugins]]" #LightGreen
    participant "[[/architect/components/plugins.scans ScansPlugin]]" as ScansPlugin
end box

box "CORE" #LightBlue
    participant "[[/architect/components/core.controller Controller]]" as Controller
    participant "[[/architect/components/core.sast SAST]]" as SAST
    participant "[[/architect/components/core.dast DAST]]" as DAST
end box

ScanStarter -> ScansPlugin: Запуск сканирования

ScansPlugin -> ConfigManager: Чтение конфигурации сканирования
ConfigManager -> ScansPlugin:

ScansPlugin -> SourceCodeManager: Чтение исходного кода приложения (если требуется)
SourceCodeManager -> ScansPlugin:

ScansPlugin -> Controller: Запуск сканирования
Controller -> SAST: Запуск сканирования
Controller -> DAST: Запуск сканирования

@enduml
