@startuml
title Workflow

actor User

box UserScope #LightBlue
    participant Repository
    participant CICD
    participant IDE
end box

box ASOC #LightGreen
    participant WorkflowManager
    participant ScanManagment
    box VulnManagment #LightGray
        participant VulnManagment
        participant Report
    end box
    participant "Scanners (COREs + Plugins)" AS Scanners
end box

group Инициация workflow
    User -> Repository: Создание release ветки
    Repository -> CICD: Запуск workflow
    CICD -> CICD: Deploy приложения на тестовый контур
    CICD -> WorkflowManager: Запуск workflow
end

WorkflowManager --> VulnManagment: Запуск workflow

VulnManagment -> Report: Создание сущности Report

WorkflowManager -> ScanManagment: Запуск скана репозитория
ScanManagment -> Scanners: Запуск скана репозитория

group Общий флоу при обнаружении уязвимости
    IDE -> VulnManagment: Уязвимость в коде
    VulnManagment -> Report: Запись уязвимости + создание агрегата
end

group Пользовать считает, что исправил уязвимость
    User -> Report: пометка fixed=true
    Report -> Report: Сохранение в истории, \n что пользователь выставил fixed=true у агрегата
    VulnManagment --> IDE: Задача на перескан
    IDE -> VulnManagment: Уязвимость не устранена
    VulnManagment -> VulnManagment: Создание еще одной сущности Vuln
    VulnManagment -> Report: Агрегат: fixed = false, reOpen = true \n Сохранение в истории, что у уязвимости поменялась статусная модель
    VulnManagment -> Report: ??? Замена в агрегате ссылки на уязвимость \n или добавление, чтобы была история ???
end

group Потверждение DAST'ом
    Scanners -> Scanners: Найдена уязвимость SAST'ом

    Scanners -> VulnManagment: Новая уязвимость
    VulnManagment -> Report: Запись уязвимости + создание агрегата

    Scanners -> Scanners: Запуск DAST для проверки
    Scanners -> Scanners: Потверждение от DAST'а
    Scanners -> VulnManagment: Потверждение уязвимости
    VulnManagment -> Report: Обогащение (!)агрегата
end

group ??? Пользовать считает, что уязвимости нет ???
    User -> Report: ??? Может ли пользователь пометить не агрегат, а только уязвимость ??? \n Например, посчитать, что SAST сфолзил. Но в данном случае было потверждение от DAST (другого SAST).
end

group ??? DAST первоисточник уязвимости ???
    Scanners -> Report: DAST обнаружил уязвимость
    Report -> Scanners: Скан SAST'ом
end

group Уязвимость, которая не потверждена DAST'ом
    IDE -> VulnManagment: Новая уязвимость
    VulnManagment -> Report: Запись уязвимости + создание агрегата

    VulnManagment -> Scanners: Запрос потверждения
    Scanners -> Scanners: Уязвимость не потверждена

    VulnManagment -> VulnManagment: Не модифицируем агрегат
end

group Пользователь изменяет правила дедупликации/корреляции
    User -> VulnManagment: Новые правила \n или модификация текущих

    VulnManagment -> Report: Определение уязвимостей в агрегате
    VulnManagment -> Report: Изменение состава агрегата \n запись в истории о модификации агрегата \n запись в истории о модификации статусной модели уязвимости
end

group Пользователь отвязывает уязвимость от агрегата (возможность ручной работы с уязвимостями и агрегатом)
    User -> Report: Пользователь отвязывает уязвимость от агрегата \n ??? привязка к новому агрегату ??? \n ??? Авто создание агрегата, если уязвимость отвязывается без привязки к другому агрегату ??? \n ??? Авто удаление агрегата, если у него больше нет уязвимостей ???
end

group Завершение workflow
    User -> WorkflowManager: Завершение workflow
    WorkflowManager --> Report: Завершение workflow
    Report -> Report: Закрытие сущности Report \n с этого момента report нельзя изменять и все его агрегаты
end

@enduml
