@startuml

skinparam linetype ortho

package "[[/entities/docs/blank?dh-doc-id=asoc.entities Entities]]" as Entities {
    class "[[/entities/docs/blank?dh-doc-id=asoc.entities.scan_settings.dast.auth_profile AuthProfile]]" as AuthProfile {}
    class ScanProfile {}
}

package "[[/architect/components/scanner_adapter ScannerAdapter]]" as ScannerAdapter {
    class "[[/architect/components/scanner_adapter.dast DASTAdapter]]" as DASTAdapter {}
}

package WebEngineAdapter {
    class DataMapper {
    }

    class WEScanProfile {
        - configEditor ConfigEditor
        + AddTarget()
    }

    class ConfigEditor {
        + Patch()
    }

    class XMLConfigEditor {
    }
}

' links

DASTAdapter o-- DataMapper

DataMapper --> WEScanProfile
DataMapper --> AuthProfile
DataMapper --> ScanProfile

WEScanProfile --> AuthProfile
WEScanProfile --> ScanProfile

ConfigEditor <|-- XMLConfigEditor
ConfigEditor <- WEScanProfile

@enduml
