@startuml
title Запуск сканирования

actor User as User

box "[[/architect/components/platform.scan_management.asoc_backend ASOC Backend]]" #LightGray
    participant "[[/architect/components/platform.scan_management.asoc_backend.wac WAC]]" as WAC
    participant "[[/architect/components/platform.scan_management.asoc_backend.wp WP]]" as WP
end box

box "[[/architect/components/scanner_adapter ScannerAdapter]]" #LightGreen
    participant "[[/architect/components/scanner_adapter.dast DASTAdapter]]" as DASTAdapter
end box

box WebEngineAdapter #Green
    participant "[[/architect/components/scanner_adapter.external.data_mapper DataMapper]]" as DataMapper
    participant "[[/architect/components/scanner_adapter.external.runner Runner]]" as Runner
    participant "[[/architect/components/scanner_adapter.external.core Core]]" as Core
end box

User -> WAC: Запрос на запуск сканирования

WAC -> WAC: Сохранение задачи на запуск сканирования
WAC --> WP: Создание задачи на запуск сканирования
WAC -> User: Ответ пользователю


WP -> DASTAdapter: Запуск скана \n передача профилей сканирования (gRPC)

DASTAdapter -> Runner: Запуск скана
Runner -> DataMapper
DataMapper -> Runner: Конвертация настроек сканирования

Runner -> Core: Запуск сканирования

@enduml
