@startuml
title Аутентификация и обращение к ресурсу с проксирующим бекендом

actor Client

participant "[[/architect/components/platform.iam.auth_proxy AuthProxy]]" as AuthProxy
participant "[[/architect/components/platform.iam.casgate Casgate]]" as Casgate
participant "Product backend (BB/AI/AF)" as ResourceBackend

Client -> ResourceBackend: Пользовательский запрос
ResourceBackend -> AuthProxy: Запрос информации о сессии пользователя

AuthProxy -> AuthProxy: Пользователь не аутентифицирован

AuthProxy -> ResourceBackend: 401 Error + login form url

ResourceBackend -> Client: Redirect to login form
Client -> Casgate: Login form
Casgate -> Casgate: Креды подошли
Casgate -> Client: Redirect на приложение
Client -> ResourceBackend: code+state
ResourceBackend -> AuthProxy: code+state
AuthProxy -> Casgate: code+state
Casgate -> AuthProxy: Tokens
AuthProxy -> ResourceBackend: session_uuid
ResourceBackend -> Client: cookie: session_uuid

@enduml
