@startuml
title Авторизация и обращение к ресурсу с проксирующим бекендом

actor Client

participant "[[/architect/components/platform.iam.auth_proxy AuthProxy]]" as AuthProxy
participant "[[/architect/components/platform.iam.casgate Casgate]]" as Casgate
participant "Product backend (BB/AI/AF)" as ResourceBackend

Client -> ResourceBackend: Пользовательский запрос
ResourceBackend -> AuthProxy: batch enforce запрос со списком полномочий

AuthProxy -> Casgate: batch enforce запрос со списком полномочий
Casgate -> AuthProxy: список bool флагов на каждую пермиссию
AuthProxy -> ResourceBackend: список разрешенных пермиссий

ResourceBackend -> ResourceBackend: разрешение/запрет выполнения пользовательского сценария \n в зависимости от респонса
ResourceBackend -> Client: статус выполненного запроса

@enduml
