@startuml
title Пример сканирования
participant "[[/architect/components/asoc.core.controller Controller]]" as Controller
participant "[[/architect/components/asoc.core.sast SAST]]" as SAST
participant "[[/architect/components/asoc.core.dast DAST]]" as DAST
group Сканирование
    Controller -> DAST: **Запуск скана**
    DAST -> Controller: **SPA** site.js

    Controller -> SAST: **Парсинг js файла**
    SAST -> Controller: **Schema**

    Controller -> DAST: **Schema**
    DAST -> Controller: **Результат сканирования**
end
@enduml
